export const PERSONAL_INFO = {
  name: "Kevin Arangú",
  shortDescription:
    "A telecommunications engineer, technology lover and resident of Venezuela.",
  networks: {
    linkedin: "https://www.linkedin.com/in/kevinarangu/",
    github: "https://github.com/KevinArangu",
  },
  photo:
    "https://lh3.googleusercontent.com/drive-viewer/AJc5JmSTO7BYt36_pQqvRztBELx3sHin9SNfk3R6wudR-EgtmZzs-nxHqOiiQlSxLs0uyCK8rJkw_mKmiLVuj4Ol5x0dKlaFuA=w1366-h657",
};

export const MY_GRADES = [
  {
    id: 1,
    title: "U.E.E Dr Argimiro Bracamonte II",
    categories: ["elementary-school"],
    comment: "2004 - 2009",
  },
  {
    id: 2,
    title: "U.E.C. Federico Froebel",
    categories: ["high-school"],
    comment: "2009 - 2014",
  },
  {
    id: 3,
    title: "Universidad Fermín Toro",
    categories: ["university"],
    comment: "2014-2020",
  },
];

export const MY_EXPERIENCE = [
  {
    id: 1,
    title: "Proyecto e Inversiones M.V. Miranda C.A.",
    categories: ["networking", "engineering"],
    comment: "March 2019 - September 2020",
  },
  {
    id: 2,
    title: "Intercom Servicios C.A.",
    categories: ["networking", "engineering", "noc"],
    comment: "October 2020 - May 2021",
  },
  {
    id: 3,
    title: "Carlatino",
    categories: ["front-end", "developer"],
    comment: "May 2021 - October 2022",
  },
  {
    id: 4,
    title: "IPCOM",
    categories: ["fullstack", "developer"],
    comment: "October 2022 - Currently",
  },
];

export const MY_COURSES = [
  {
    id: 1,
    title: "CCNA Switching & Routing: Networking Introduction",
    description: "Cisco Networking Academy",
    comment: "November 2016",
    href: "",
    image: "",
  },
  {
    id: 2,
    title: "CCTV System Technician",
    description: "CADIF1 Academy",
    comment: "March 2018",
    href: "",
    image: "",
  },
  {
    id: 3,
    title: "CCNA Switching & Routing: Routing and Switching Basics",
    description: "Cisco Networking Academy",
    comment: "August 2018",
    href: "",
    image: "",
  },
  {
    id: 4,
    title: "Backhaul IP Networks",
    description: "Telecapp Academy",
    comment: "December 2019",
    href: "",
    image: "",
  },
  {
    id: 5,
    title: "Long Term Evolution (LTE)",
    description: "Telecapp Academy",
    comment: "February 2020",
    href: "",
    image: "",
  },
  {
    id: 6,
    title: "IP/MPLS Traffic Engineering",
    description: "Telecapp Academy",
    comment: "March 2020",
    href: "",
    image: "",
  },
  {
    id: 7,
    title: "Javascript Master",
    description: "Udemy Academy",
    comment: "April 2020",
    href: "",
    image: "",
  },
  {
    id: 8,
    title: "Cloud Computing",
    description: "Google",
    comment: "September 2020",
    href: "",
    image: "",
  },
  {
    id: 9,
    title: "Introduction to Terminal and command line",
    description: "Platzi",
    comment: "March 2021",
    href: "",
    image: "",
  },
  {
    id: 10,
    title: "Alpine.js",
    description: "Codigo Facilito Academy",
    comment: "June 2021",
    href: "",
    image: "",
  },
  {
    id: 11,
    title: "TailwindCSS",
    description: "Platzi",
    comment: "July 2021",
    href: "",
    image: "",
  },
  {
    id: 12,
    title: "Next.js",
    description: "Platzi",
    comment: "March 2022",
    href: "",
    image: "",
  },
  {
    id: 13,
    title: "Git & GitHub",
    description: "Platzi",
    comment: "March 2022",
    href: "",
    image: "",
  },
  {
    id: 14,
    title: "Software Engineering Fundamentals",
    description: "Platzi",
    comment: "April 2022",
    href: "",
    image: "",
  },
  {
    id: 15,
    title: "High Concurrency Architectures",
    description: "Platzi",
    comment: "August 2022",
    href: "",
    image: "",
  },
  {
    id: 16,
    title: "Amazon Web Services: Cloud Computing Fundamentals",
    description: "Platzi",
    comment: "August 2022",
    href: "",
    image: "",
  },
  {
    id: 17,
    title: "Amazon Web Services: Compute, Storage & Databases",
    description: "Platzi",
    comment: "August 2022",
    href: "",
    image: "",
  },
  {
    id: 18,
    title: "Amazon Web Services: Networks, Governance & Machine Learning",
    description: "Platzi",
    comment: "August 2022",
    href: "",
    image: "",
  },
  {
    id: 19,
    title: "Vue.js: Introduction",
    description: "Platzi",
    comment: "September 2022",
    href: "",
    image: "",
  },
  {
    id: 19,
    title: "Vue.js: Components & Composition API",
    description: "Platzi",
    comment: "September 2022",
    href: "",
    image: "",
  },
  {
    id: 20,
    title: "Vue.js: Practices",
    description: "Platzi",
    comment: "Octuber 2022",
    href: "",
    image: "",
  },
  {
    id: 21,
    title: "Typescript Fundamentals",
    description: "Platzi",
    comment: "Octuber 2022",
    href: "",
    image: "",
  },
  {
    id: 22,
    title: "Node.js: API REST with Express",
    description: "Platzi",
    comment: "Octuber 2022",
    href: "",
    image: "",
  },
].reverse();

export const USES = [
  "Javascript",
  "Alpine.js",
  "React",
  "Next.js",
  "react-use-form",
  "Swiper.js",
  "react-hot-toast",
  "Node.js",
  "Express.js",
  "@hapi/boom",
  "next-auth",
  "stytch",
  "Axios",
  "next-i18next",
  "HTML",
  "CSS",
  "TailwindCSS",
  "Typescript",
  "Amazon Web Services",
  "Linux",
  "Windows",
  "VS Code",
  "Vercel",
  "Illustrator",
  "npm",
  "Git",
  "Github",
  "Cisco",
  "Mikrotik",
  "Ubiquiti",
  "Huawei",
  "Terminal",
  "SSH",
  "CMD",
  "PowerShell",
  "BASH",
  "framer-motion",
  "Prettier",
  "ESLint",
  "tailwind-styled-components",
  "dotenv",
  "Multer",
  "Joy",
];
